name: test
on:
  push:
    branches:
      - '*'
      - '!master'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10','11', '12', '13', '14', '15', '16', '17', '18']
    name: NodeJS ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm run dtslint